### ISSUE TITLE
Add nightly builds

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/yarn#1474]
Provide an easy way for users to get the latest and greatest version of Yarn!

To be done:
- [x] Set unique version number for dev builds (done: #1230)
- [x] Create `nightly.yarnpkg.com` subdomain
- [x] Archive builds from CircleCI (#1473)
- [x] Archive builds from AppVeyor (done: #1631)
- [x] Create `nightly.yarnpkg.com/latest-version` endpoint to return latest version number (analogous to the current https://yarnpkg.com/latest-version).
- [x] Pretty directory listing (maybe tabs per artifact type, and latest release at the top?)
- [x] Create Debian repo for nightly builds, using .debs from CircleCI
- [x] Update end-to-end tests (#1391) to use nightly Debian repo
- [x] Update installation script to have a `--nightly` flag
- [x] Update docs on site (https://github.com/yarnpkg/website/pull/245)

**Comment by Daniel15** [comment]
Mostly done, just needs docs. https://nightly.yarnpkg.com/ is up, and there's a Debian/Ubuntu repo at https://nightly.yarnpkg.com/debian/. The install script has a `--nightly` flag  to install the latest nightly build.

**Comment by Daniel15** [comment]
Done! Documented, and end-to-end tests are using the nightly builds now too.
