### ISSUE TITLE
Fixes to cherry-pick in [0.17-stable]

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#1859]
0.17.0
- [x] Don't output list if all dependencies are up to date - https://github.com/yarnpkg/yarn/commit/567f8af51ab6ce67d345177ccc4cc514680827fd
- [x] Fix `expected manifest` on global add #1855 https://github.com/yarnpkg/yarn/commit/16a5268f1702fbfa54b89b995d7e86f48cb568bf
- [x] ENOENT: no such file or directory, chmod - https://github.com/yarnpkg/yarn/issues/1853 #1823
----  
0.17.2 branch cut
- [x] Yarn global add doesn't add the binary #1886 #1889 https://github.com/yarnpkg/yarn/commit/b76ac934a2d738aaf8c103801c8dc7f80ba8cf3f
- [x] `yarn install` not generating missing lockfile - https://github.com/yarnpkg/yarn/issues/1876 https://github.com/yarnpkg/yarn/commit/135fd87661a78e982283e086863ba7a76546a789
- [x] No such file file or directory, lstat - https://github.com/yarnpkg/yarn/issues/1834 #1836 #1831 #1818 #1871 (https://github.com/yarnpkg/yarn/commit/1180f0fb0e20281cf09303d18281ff9f6a0e2e6a)
- [x] node-pre-gyp: not found https://github.com/yarnpkg/yarn/issues/1838 #1817
----  
0.17.3 branch cut
- [x]  roadrunner.json #1724 (https://github.com/yarnpkg/yarn/commit/4ce67f3d5da3ba99c3e8718100883e9f145ce125)
----
0.17.4 branch cut
- [x] bcrypt build regression #1848 (fix https://github.com/yarnpkg/yarn/commit/3f765c354306bd8e6ca22b3bb333542d1a8fd6e2)
- [x] node-sass build artifact - #1872 #1832 (can't repro)
- [x] install script + .npmrc https://github.com/yarnpkg/yarn/issues/1852 (no one can repro, something odd with .npmrc)
---- 
0.17.6 branch cut
- [x] add a cache breaker to the yarn cache based on the current version to prevent dependency shifting (fix #1965)
---- 
0.17.7, 0.17.8 branch cut
- [x] yarn install --verbose #763 (cbdef6639664d1bd098d459a06dd2168b3a6db4b)
---- 
0.17.9 branch cut
- [x] Fixes race condition on yarn install mutex network #2092 718d4ed9ccbd1b4c945991ba353708a2d111db43
---- 
0.17.10 branch cut

---- NOT CHERRY PICKED, WILL BE RELEASED IN 0.18
- [x] Scoped package installation sometimes fails on Windows #1861 (fix #1866) 
- [x] authentication for scoped private registry tarballs #1666 #1318

**Comment by dbashford** [comment]
If this is you guys figuring out what needs to be prioritized for the next release... I think #1823 has made Yarn unusable for a lot of folks.

**Comment by bestander** [comment]
Thanks, @dbashford, yes, help with prioritization, fixes and tests is very much welcome

**Comment by cpojer** [comment]
Thanks @bestander for trying to be on top of this. I know it's hard with all the issues/PRs coming in. Once we get to better test coverage we should figure out how we can focus on making the project a bit less of a burden to maintain :)

**Comment by Daniel15** [comment]
Just thought I'd mention that most installation methods have been rolled back to 0.16.1 until we fix the major issues. Sorry for the churn!

We'll be sure to add some more automated tests to catch all these issues if they ever occur again in the future. The end-to-end test we currently have is very simple (start Ubuntu Docker container, install Yarn, install React using Yarn), we'll definitely add more scenarios to it 😄

**Comment by bestander** [comment]
0.17.3 is being deployed, please send more PRs and let us know what is the highest pri now

**Comment by KidkArolis** [comment]
Consider pulling in #1666, it fixes yarn for use with private authenticated registries.

**Comment by bestander** [comment]
@KidkArolis I've added it to the list but to the bottom considering that it is still in progress and is not a regression (right?).

**Comment by KidkArolis** [comment]
Thanks, nw.

**Comment by Daniel15** [comment]
I think the roadrunner.json issue is fairly important to fix.

**Comment by bestander** [comment]
Everything that people could consistently reproduce has been fixed and cherry-picked into 0.17.4 which is being released now.

**Comment by SimenB** [comment]
@bestander #761

**Comment by bestander** [comment]
@SimenB, I understand this is an ongoing issue and not a regression.

**Comment by SimenB** [comment]
It was made worse in 0.17. We had `yarn --prod` which worked, and with 0.17 it broke. My repro breaks in both 0.16 and 0.17 though

**Comment by bestander** [comment]
@SimenB, ok, we'll get this in

**Comment by owais** [comment]
Just tried 0.17.9 on OS X but it still doesn't seem to fix the private tarballs issue. Should I open another issue for this or did we not actually roll out the fix yet?

```
Trace:
  Error: http://npm.ezhome.io:8080/@/@my-company/mypackage/_attachments/mypackage-3.7.2.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.flush (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
      at BlockStream.end (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
      at Extract.Parse.end (/usr/local/Cellar/yarn/0.17.9/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
      at UnpackStream.onend (_stream_readable.js:511:10)
```

**Comment by bestander** [comment]
Hey guys, I'd like to not cherry-pick the last two:
 Scoped package installation sometimes fails on Windows #1861 (fix #1866)
 authentication for scoped private registry tarballs #1666 #1318

And release 0.18.0 with them during the weekend.
Cherry-picking got a bit harder with master branch diverging

**Comment by bestander** [comment]
0.18 released
