### ISSUE TITLE
Fixes to cherry-pick into 0.19-stable

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#2499]
- [x] #2491 - `yarn version` broken - fix https://github.com/yarnpkg/yarn/commit/d66575e2b03a80aa9c08578a7e28d9e745faa836
- [ ] #2439 - `yarn check` output style is escaping colors
- [x] Treat some configs as internal to fix #2286. (#2422)

**Comment by bestander** [comment]
I can release 0.19.2, the fixes are in the branch.
However 0.20.1 has them, too, and is ready for release, so maybe 0.19 patch is not needed?
