### ISSUE TITLE
Follow up on release 0.27.3

### ISSUE THREAD

**Issue by bestander** [yarnpkg/yarn#3769]
- [x] #3759 was reverted because of jest complains, need to reland it with the fixes
- [x] We don't have tests that cover how current Yarn will run Yarn's jest tests https://github.com/yarnpkg/yarn/issues/3767. Circle CI could compile Yarn and use it to drive `test-ci` command
- [ ] We don't cover private packages installation e2e https://github.com/yarnpkg/yarn/issues/3765

**Comment by Daniel15** [comment]
> We don't have tests that cover how current Yarn will run Yarn's jest tests [#3767](https://github.com/yarnpkg/yarn/issues/3767). Circle CI could compile Yarn and use it to drive `test-ci` command

We could make CircleCI use the latest nightly build of Yarn, rather than the current release build. This would help us more easily catch issues with Yarn itself. That's a one-line change in `scripts/bootstrap-env-ubuntu.sh`:
```
-echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
+echo "deb http://nightly.yarnpkg.com/debian/ nightly main" | sudo tee /etc/apt/sources.list.d/yarn.list
```

Or the RC instead.

Having said that, that also means that a broken version of Yarn would also break the build, and the build won't be fixed until the fix is committed 😕

**Comment by bestander** [comment]
I think nightly on Circle and stable on Travis could be a good mix.

**Comment by Daniel15** [comment]
Given CircleCI is the backbone of our release infra, it might be safer to use nightly on Travis 😛

**Comment by bestander** [comment]
True!

**Comment by bestander** [comment]
As a matter of fact Circle is using yarn v0.21.3 and is green.
We might configure one matrix rule on Travis to run on nightly (or compiled current)

**Comment by arcanis** [comment]
Re: private packages; I've setup a private package at @arcanis/private-pkg for debugging and fixing the issue, but it would be better to have something on the @yarnpkg organization.

**Comment by BYK** [comment]
@bestander I did the second item on Travis CI instead since it was easier: https://github.com/yarnpkg/yarn/pull/3805

**Comment by BYK** [comment]
I've filed #4186 for the last checkbox and am going to close this ticket in favor of the more granular issues.
