### ISSUE TITLE
Compatibility Checklist

### ISSUE THREAD

**Issue by wycats** [yarnpkg/yarn#392]
This issue tracks open source projects we want to test against yarn.

I added a couple of items but please feel free to fill it up with open source projects we want to smoke test (see #375) before releasing.
### Packages
- [ ] [Top 1000 on npm](https://gist.github.com/anvaka/8e8fa57c7ee1350e3491#top-1000-most-depended-upon-packages)
### Apps
- [ ] [Ghost](https://github.com/tryghost/ghost)
### CLI Tools

Probably makes sense to run the test suite using yarn, and also try to manually smoke test that it works correctly, assuming we do #227.
- [ ] [Ember CLI](https://github.com/ember-cli/ember-cli)
- [ ] [Babel CLI](https://github.com/babel/babel/tree/master/packages/babel-cli)
- [ ] [Create React App](https://github.com/facebookincubator/create-react-app)
- [ ] [Angular CLI](https://github.com/angular/angular-cli)
- [ ] [Polymer CLI](https://github.com/Polymer/polymer-cli)
- [ ] [Grunt](https://github.com/gruntjs/grunt-cli)
- [ ] [Gulp](https://github.com/gulpjs/gulp-cli)
- [ ] [flow-bin](https://www.npmjs.com/package/flow-bin)
- [ ] [tsc](https://github.com/Microsoft/TypeScript)
- [ ] [Typings (TypeScript)](https://github.com/typings/typings)
- [ ] [Express Generator](https://github.com/expressjs/generator)
- [ ] [Webpack](https://github.com/webpack/webpack)

**Comment by vitorbal** [comment]
How about [eslint](https://github.com/eslint/eslint) for the CLI Tools section?

**Comment by FLGMwt** [comment]
Did some exploration for the top 1000 depended upon and ended up with a pretty short list: https://github.com/FLGMwt/yarncompat/blob/master/package.json (referencing these packages, not developing them. I figured that was the initial intent at least)

I've done zero investigation for failure reasons, but I'll find some time to poke around.

**Comment by lcrespom** [comment]
FYI, I did "yarn global add angular-cli" and failed.
Then I did "npm install angular-cli -g" and it worked.

**Comment by reflog** [comment]
same here. also, on a new 'ng new' project, yarn fails due to 'zopfli' problems.

**Comment by TimvdLippe** [comment]
`yarn global add polymer-cli@next` properly works. `polymer --version` shows that it is working :tada:

**Comment by bestander** [comment]
I think it is outdated now, compatibility will be fixed on issues by issue basis
